#!/usr/bin/env python
# -*- coding: utf-8 -*-

from splinter import Browser
import requests
import json
import sys
import os


def remove_bars(site_name):
    site_name_size = len(site_name)-1

    if site_name[site_name_size] == '/':
        site_name = site_name[0:site_name_size]
        return remove_bars(site_name)
    else:
        return site_name


def main():
    try:
        site_name = str(sys.argv[1])
    except Exception as ex:
        print('Insert URL to access site.json file')
        print(ex)
        sys.exit(-1)

    site_name_clean = remove_bars(site_name)

    req = requests.get(site_name_clean + '/site.json')
    if req.status_code != 200:
        print('Only OK! This response is ' + req.status_code)
        sys.exit(-1)

    output_dir = 'output'
    if not os.path.exists(output_dir):
        os.makedirs(output_dir)
        os.chdir(output_dir)

    j = json.loads(req.text)
    for i in j['pages']:
        browser = Browser('firefox')
        browser.visit(i['url'])
        if browser.status_code.is_success():
            str_replaced = i['title'].replace(" ", "-")
            browser.driver.save_screenshot(str_replaced + '.png')
        browser.quit()

if __name__ == '__main__':
    main()
